# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tourapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderAvailabilityManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tourapi.models.set_sp_image_url)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvidersCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvidersLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.Languages')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.ServiceProviders')),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
            ],
            managers=[
                ('publics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TourismGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('start_date', models.DateTimeField(auto_created=True)),
                ('is_tourist_care', models.BooleanField(default=False)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.ServiceProviders')),
                ('tourism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.Tourism')),
            ],
        ),
        migrations.CreateModel(
            name='TourismGuidePlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapi.Places')),
                ('tourism_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.TourismGuide')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('text', models.TextField()),
                ('tourism_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.TourismGuide')),
            ],
        ),
        migrations.AddField(
            model_name='tourism',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.Tourist'),
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.ServiceProvidersCategories'),
        ),
        migrations.AddField(
            model_name='serviceproviderfeedback',
            name='tourism_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapi.TourismGuide'),
        ),
        migrations.AddField(
            model_name='places',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.ServiceProviders'),
        ),
        migrations.AddField(
            model_name='placeactivities',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapi.Places'),
        ),
    ]
