# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tourapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProviderAvailabilityManager',
        ),
        migrations.AlterModelManagers(
            name='serviceproviders',
            managers=[
                ('availables', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
